### ISSUE TITLE
`Pagemove throttle for new users` : file move get rejected due to speed.

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#28]
I got `filemover` userrights on Commons for my bot :
* 1st rename worked 🥇  
* 2nd revert-renamed was blocked and the bot visibly temporally lost its moving rights.

Any familiarity with this error message ?

```bash
Error: abusefilter-autopromote-blocked: This action has been automatically identified as harmful, and it has been disallowed. In addition, as a security measure, some privileges routinely granted to established accounts have been temporarily revoked from your account. A brief description of the abuse rule which your action matched is: Pagemove throttle for new users
    at /home/yug/Documents/DragonsBot/node_modules/cejs/application/net/wiki/admin.js:166:15
    at check_session_badtoken (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/wiki/query.js:181:4)
    at /home/yug/Documents/DragonsBot/node_modules/cejs/application/net/wiki/query.js:603:4
    at IncomingMessage.<anonymous> (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:2221:6)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

If I remember well, we are limited to 1 edit every 5 secs. But I can't get my hand on the doc at the moment, and renaming may have special rules.

If you don't know no need to look for the answer : I asked on Commons for guidance.

**Comment by hugolpz** [comment]
Commons admin granted my bot autopatroller userright.
