### ISSUE TITLE
`TypeError: item.includes is not a function` when uploading.

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#29]
Following up for yesterday upload issue. Down the road I now meet this :

```bash
$ node ./create-Commons-upload.js
Connecting...
get_API_parameters: Set enwiki: path=query+siteinfo                    # <------- Side issue: why talk about enwiki ? My target is Commons.
get_API_parameters: Set commonswiki: path=query+siteinfo
Username ShufaBot@ShufaBot is connected !
wiki_API_page: Not exists: [[:File:A-red.png]]                         # <------- this is good, I want to upload when page is empty
get_API_parameters: Set commonswiki: path=upload
/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:553
			: !item.includes(boundary);
			        ^

TypeError: item.includes is not a function                              # <------- This is the rocks on the road ! 
    at not_includes_in (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:553:12)
    at Array.every (<anonymous>)
    at not_includes_in (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:551:38)
    at Array.every (<anonymous>)
    at not_includes_in (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:551:38)
    at give_boundary (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:570:9)
    at process_next (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:712:5)
    at process_next (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:790:4)
    at push_and_callback (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:630:5)
    at get_file_object (/home/yug/Documents/DragonsBot/node_modules/cejs/application/net/Ajax.js:661:5)
```

**Comment by kanasimi** [comment]
When we can not read, it will throw now.

**Comment by hugolpz** [comment]
Still fails on my side. I did npm update. Need to publish the fix or else ?

**Comment by kanasimi** [comment]
I make a debug version. May you update to the latest version, and un-comment https://github.com/kanasimi/CeJS/commit/25432fa0e026a0a02a671d19f4dd99a39fdc81d2#diff-678626254263abe7a9e4f91dab2070aa8f24508bf2f96a31acf9d9b5ef8316b4R553 to see what item is?

**Comment by hugolpz** [comment]
I'm not very fluent in NodeJS so I didn't understand your previous messages. Please give me slower-clearer guidance on this issue.

### May you update to the latest version ?
`$npm update` says I'am already up to date. Last npm publication was 4 days ago.

```bash
$ npm v cejs
cejs@4.1.14 | BSD-3-Clause | deps: none | versions: 118
...
latest: 4.1.14 
published 4 days ago by vimunci <vimunci@gmail.com>
```

```bash
$ npm v wikiapi
wikiapi@1.14.1 | BSD-3-Clause | deps: 1 | versions: 24
...
latest: 1.14.1  
published a month ago by vimunci <vimunci@gmail.com>
```

**Comment by hugolpz** [comment]
I changed `ignorewarnings: true` into `ignorewarnings: 1` and it works again. 🤦🏼 🤣

**Comment by kanasimi** [comment]
It should works now even you using `ignorewarnings: true`.
