### ISSUE TITLE
"Too many values supplied for parameter \"pageids\". The limit is 50."

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#52]
Given the code :
```javascript
const Wikiapi= require('wikiapi');
const logins = require('./logins.js');

// Login credentials from .login*.js
var USER = logins.commons.user,
	PASS = logins.commons.pass,
	API  = logins.commons.api;

(async () => {
    // Connect
    var targetwiki = new Wikiapi;
    await targetwiki.login(USER, PASS, API);
    console.log(`Username ${USER.split('@')[0]} is connected !`);

/* *************************************************************** */
/* CORE ACTION(S) HERE : HACK ME ! ******************************* */
    // List of categories
    var categories = (await targetwiki.category_tree('Lingua_Libre_pronunciation', { depth: 1, cmtype: 'subcat', get_flated_subcategories: true })).flated_subcategories;
    keys=Object.keys(categories)
    console.log(keys.length+' keys :\n '+JSON.stringify(keys))
    
/* END CORE ****************************************************** */
/* *************************************************************** */
})();
```

Update cejs done:
```bash
~/Documents/WikiapiJS-Eggs$ node GitHub.updater.node.js
Read the latest version from cache file CeJS-master.version.json
Get the infomation of latest version of CeJS...
Already have the latest version: 2022-01-05T08:20:26Z
```

Due to `.category_tree()`, the script prints the following warning message, while the script continue to work fine :
```bash
/Documents/WikiapiJS-Eggs$ node wiki-category_tree-many.js 
get_API_parameters: Cache commonswiki: path=query+siteinfo
Username ShufaBot is connected !
get_list: Unknown response: [{"error":{"code":"toomanyvalues","info":"Too many values supplied for parameter \"pageids\". The limit is 50.","limit":50,"lowlimit":50,"highlimit":500,"*":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."},"servedby":"mw1363"}]
Trace: {
  error: {
    code: 'toomanyvalues',
    info: 'Too many values supplied for parameter "pageids". The limit is 50.',
    limit: 50,
    lowlimit: 50,
    highlimit: 500,
    '*': 'See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes.'
  },
  servedby: 'mw1363'
}
    at wiki_API_list_callback (/home/yug/Documents/WikiapiJS-Eggs/node_modules/wikiapi/node_modules/cejs/application/net/wiki/list.js:1075:13)
    at wiki_API_next_list_callback (/home/yug/Documents/WikiapiJS-Eggs/node_modules/wikiapi/node_modules/cejs/application/net/wiki/task.js:571:16)
    at /home/yug/Documents/WikiapiJS-Eggs/node_modules/wikiapi/node_modules/cejs/application/net/wiki/list.js:587:5
    at check_session_badtoken (/home/yug/Documents/WikiapiJS-Eggs/node_modules/wikiapi/node_modules/cejs/application/net/wiki/query.js:189:4)
    at XMLHttp_handler (/home/yug/Documents/WikiapiJS-Eggs/node_modules/wikiapi/node_modules/cejs/application/net/wiki/query.js:687:4)
    at IncomingMessage.<anonymous> (/home/yug/Documents/WikiapiJS-Eggs/node_modules/wikiapi/node_modules/cejs/application/net/Ajax.js:2265:6)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1340:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
for_category_info_list: [object Object]
^Cpth 2/1: 17/131 Lingua Libre pronunciation-bdu: 0 item(s).    evels left)  
```

**Comment by kanasimi** [comment]
I update the code. Please check if the new version works.

**Comment by hugolpz** [comment]
(I will travel for 4 days. Not sure when i can check this.)

**Comment by kanasimi** [comment]
Wish you a happy new year holiday 😸

**Comment by hugolpz** [comment]
(I have difficulties updating dependencies directly from github).
(My `package.json` contains )
```js
  "dependencies": {
    "cejs": "github:kanasimi/CeJS",
    "npm-check-updates": "^11.1.10",
    "wikiapi":  "github:kanasimi/wikiapi"
  }
```
(`npm install` doesn't get the last github version.)

**Comment by kanasimi** [comment]
You may use GitHub.updater.node.js:
```
cd /tmp
mkdir CeJS && cd CeJS
wget "https://raw.githubusercontent.com/kanasimi/gh-updater/master/GitHub.updater.node.js" || curl -O https://raw.githubusercontent.com/kanasimi/gh-updater/master/GitHub.updater.node.js
# This script will download + extract CeJS library at ./CeJS-master.
node GitHub.updater.node.js
```

**Comment by hugolpz** [comment]
I'am back home.
This does a global install of cejs right ?

**Comment by kanasimi** [comment]
1.  GitHub.updater.node.js will put the cejs in `CeJS-master/`, you may need to move it in hand?
2. You may want to try this?
```
await targetwiki.download(targetwiki.to_namespace(masterCategory, 'Category'), { directory: `${directory}` });
```

**Comment by hugolpz** [comment]
@kanasimi hello,
I was successful with GitHub.updater.node.js including the `mv` 👍🏼. The warning is still here.
Script still works, but I just point you there is a long warning message which seems atypical or a dev mode legacy.

I edited the issue to clarify this is a `.category_tree()` warning, not related to `.download()`. I believe your point n⁰2 is related to #51 .

**Comment by kanasimi** [comment]
Hi. For https://github.com/hugolpz/WikiapiJS-Eggs/blob/main/wiki-download_by_root_category-many.js
You may try this:
```
// PURPOSE: Script to upload targets using an external data file.
// Run: $node wiki-upload-many.js
const fs = require('fs');
const Wikiapi= require('wikiapi');
const logins = require('./logins.js');

(async () => {
    // Connect
    var targetwiki = new Wikiapi;
    // Login credentials from .login*.js
    await targetwiki.login({user_name:logins.commons.user_name, password:logins.commons.pass, API_URL:logins.commons.api});
    console.log(`Username ${USER.split('@')[0]} is connected !`);

/* *************************************************************** */
/* CORE ACTION(S) HERE : HACK ME ! ******************************* */
    // Settings
    var directory = './downloads/',
        masterCategory = 'Lingua_Libre_pronunciation',
        filterCategoriesStr = 'cmn', // Category name must contain. Set to null if not required.
        filterFilesStr = 'Assassas'; // File name must contain. Set to null if not required.

    await targetwiki.download(targetwiki.to_namespace(masterCategory, 'Category'), { directory });
/* END CORE ****************************************************** */
/* *************************************************************** */
})();
```

You may also change the format in logins.js
so you can use `await targetwiki.login(logins.commons);`

**Comment by kanasimi** [comment]
@hugolpz Hi. Is the method [above](#issuecomment-1005655208) works? If it works, maybe we can close this issue and #51.

**Comment by hugolpz** [comment]
(It was throwing an error. I'm back on other IRL things for the moment. Will come back later on.)

**Comment by hugolpz** [comment]
(👍🏼 )

**Comment by hugolpz** [comment]
### Nodejs
```javascript
await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { './downloads' });
```

### Shell
```bash
~/Documents/WikiapiJS-Eggs/tmp$ node GitHub.updater.node.js 
Read the latest version from cache file CeJS-master.version.json
Get the infomation of latest version of CeJS...
Already have the latest version: 2022-01-10T08:20:58Z
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs/tmp$ node wiki-category_tree-many.js 
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/home/yug/Documents/WikiapiJS-Eggs/tmp/wiki-category_tree-many.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.0.1
```

**Comment by hugolpz** [comment]
### Nodejs
```javascript
await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { './downloads' });
```

### Shell
```bash
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs/tmp$ node GitHub.updater.node.js 
Read the latest version from cache file CeJS-master.version.json
Get the infomation of latest version of CeJS...
Already have the latest version: 2022-01-10T08:20:58Z
```

```bash
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs$ node wiki-category_tree-many.js 
/home/yug/Documents/WikiapiJS-Eggs/wiki-category_tree-many.js:26
    await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { './downloads' });
                                                                                                   ^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.0.1
```

**Comment by hugolpz** [comment]
As for closing #51, the benchmarks I did suggest the proposal improvement haven't been integrate.

Do you mean that `    await targetwiki.download(targetwiki.to_namespace(masterCategory, 'Category'), { directory });` is expected to be that implementation ? (I need more explanation from you).

**Comment by kanasimi** [comment]
```{ directory }``` means ```{ directory:directory }```, so you may use ```{ directory:directory }``` as well.

**Comment by hugolpz** [comment]
The directory in which I want to store all those downloads is `./downloads` and this directory exists.
I tested the following:

## Full code
```javascript
// PURPOSE: Given a root category, script list subcategories and download all files from them into dedicated repositories.
// Run: $node script.js
const Wikiapi= require('wikiapi');
const logins = require('./logins.js');

// Login credentials from .login*.js
var USER = logins.commons.user,
	PASS = logins.commons.pass,
	API  = logins.commons.api;

(async () => {
    // Connect
    var targetwiki = new Wikiapi;
    await targetwiki.login(USER, PASS, API);
    console.log(`Username ${USER.split('@')[0]} is connected !`);

    // CORE CODE
    await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { './downloads' });

})();
```

## Variations
### `{ './downloads' }`
```javascript
await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { './downloads' });
```

```bash
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs$ node wiki-category_tree-many.js 
/home/yug/Documents/WikiapiJS-Eggs/wiki-category_tree-many.js:26
    await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { './downloads' });
                                                                                                   ^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.0.1
```

### `{ 'downloads' }`
```javascript
await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { './downloads' });
```

```bash
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs$ node wiki-category_tree-many.js 
/home/yug/Documents/WikiapiJS-Eggs/wiki-category_tree-many.js:26
    await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { 'downloads' });
                                                                                                   ^^^^^^^^^^^

SyntaxError: Unexpected string
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.0.1
```

###  `{ directory: './downloads' }`
```javascript
    await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { directory: './downloads' });
```

```bash
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs$ node wiki-category_tree-many.js 
get_API_parameters: Cache commonswiki: path=query+siteinfo
Username ShufaBot is connected !
Cannot download Category:Lingua Libre pronunciation
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v17.0.1
```

### `{ directory }`
```javascript
    await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { directory });
```

```bash
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs$ node wiki-category_tree-many.js 
get_API_parameters: Cache commonswiki: path=query+siteinfo
Username ShufaBot is connected !
/home/yug/Documents/WikiapiJS-Eggs/wiki-category_tree-many.js:26
    await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { directory });
                                                                                                   ^

ReferenceError: directory is not defined
    at /home/yug/Documents/WikiapiJS-Eggs/wiki-category_tree-many.js:26:100
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.0.1
```

### `{ directory: directory }`
```javascript
    await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { directory: directory });
```

```bash
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs$ node wiki-category_tree-many.js 
get_API_parameters: Cache commonswiki: path=query+siteinfo
Username ShufaBot is connected !
/home/yug/Documents/WikiapiJS-Eggs/wiki-category_tree-many.js:26
    await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { directory: directory });
                                                                                                              ^
ReferenceError: directory is not defined
    at /home/yug/Documents/WikiapiJS-Eggs/wiki-category_tree-many.js:26:111
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.0.1
``````

**Comment by kanasimi** [comment]
```{ directory: './downloads' }``` should work. Can you post the full code or update https://github.com/hugolpz/WikiapiJS-Eggs/blob/main/wiki-download_by_root_category-many.js so I can know where is going wrong?

**Comment by hugolpz** [comment]
Pushed there https://github.com/hugolpz/WikiapiJS-Eggs/blob/main/wiki-download-many-category_tree_and_files.js .
 
 I redeleted cejs by hand, deleted the .json as well, redownloaded it :

 ```bash
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs/tmp$ node GitHub.updater.node.js 
Read the latest version from cache file CeJS-master.version.json
Get the infomation of latest version of CeJS...
Already have the latest version: 2022-01-11T08:15:19Z
``` 

```javascript
      await targetwiki.download(targetwiki.to_namespace('Lingua_Libre_pronunciation', 'Category'), { directory: './downloads' });
```

Still returns that error:
```bash
Cannot download Category:Lingua Libre pronunciation
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v17.0.1
```

**Comment by kanasimi** [comment]
It's strange that I successfully downloaded the files. Do you move the CeJS-master directory to node_modules/cejs?

**Comment by hugolpz** [comment]
Yes i did. (checking and redoing it for a 6th times 👀  )

**Comment by kanasimi** [comment]
How about remove ```try{...} catch(e){...}``` so we can know the stacks?

**Comment by hugolpz** [comment]
Redone : 

```bash
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs/tmp$ cp -R ./CeJS-master ../node_modules/cejs
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs/tmp$ node GitHub.updater.node.js
Read the latest version from cache file CeJS-master.version.json
Get the infomation of latest version of CeJS...
Already have the latest version: 2022-01-11T08:15:19Z
```

Error messages without and with `try{...} catch(e){...}` today are same as in [this](https://github.com/kanasimi/wikiapi/issues/52#issuecomment-1009126675). 

yug@yug-k401ub:~/Documents/WikiapiJS-Eggs/tmp$ cp -R ./CeJS-master ../node_modules/cejs
yug@yug-k401ub:~/Documents/WikiapiJS-Eggs/tmp$ node GitHub.updater.node.js
Read the latest version from cache file CeJS-master.version.json
Get the infomation of latest version of CeJS...
Already have the latest version: 2022-01-11T08:15:19Z

**Comment by kanasimi** [comment]
I still think it is caused. I make a new version 4.4.3. You can run `npm update` to get it, and show `CeL.version` to verify  what version you are using.

**Comment by hugolpz** [comment]
`console.log(CeL.version);` returns `4.4.2`, yes.

**Comment by hugolpz** [comment]
Thanks ! Issue was fixed by your code and me updating the package.
